// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOiHmPvyVPObeC0kNPY2rekWntixMN-AM',
    appId: '1:605928320502:web:bfda9af525b6bac79e6bd7',
    messagingSenderId: '605928320502',
    projectId: 'expense-tracker-81f5c',
    authDomain: 'expense-tracker-81f5c.firebaseapp.com',
    storageBucket: 'expense-tracker-81f5c.appspot.com',
    measurementId: 'G-8M9BTG143Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGthC7rXqohiWsEVdPpclFShnF46karjY',
    appId: '1:605928320502:android:5ed076ff86d909999e6bd7',
    messagingSenderId: '605928320502',
    projectId: 'expense-tracker-81f5c',
    storageBucket: 'expense-tracker-81f5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNFoUBRAbGCT-YM7pH4U1UN8vSdHjdv2s',
    appId: '1:605928320502:ios:e5ed4097b21cf01f9e6bd7',
    messagingSenderId: '605928320502',
    projectId: 'expense-tracker-81f5c',
    storageBucket: 'expense-tracker-81f5c.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );
}
